## Antibody Modelling Function for human (179 Individuals)
## Create S-Fig-4


######### required packages ############
```{r}
required_packages <- c('dplyr', 'deSolve', 'ggplot2','purrr')

install_and_load <- function(packages) {
  for (pkg in packages) {
    if (!require(pkg, character.only = TRUE)) {  
      install.packages(pkg, dependencies = TRUE) 
      library(pkg, character.only = TRUE)        
    } else {
      library(pkg, character.only = TRUE)        
    }
  }
}

install_and_load(required_packages)
```

########### read parameter ############
```{r}
pop <- read.csv("populationParameters.txt",  row.names = 1)
```

######## Set time range ###########
```{r}
Tmin <- 0
Tmax <- 180 
step_size <- 0.005
times<-c(seq(Tmin,Tmax,step_size))
```



######### Simulate population trajectory ############
```{r}
ode_ab_pop <- function(pars) {
  
  k1 <- as.numeric(pars[1]) # Growth rate in phase 1
  k2 <- as.numeric(pars[2]) # Decay rate in phase 2
  A0 <- as.numeric(pars[3]) # Initial condition
  C <- as.numeric(pars[4])  # Carrying capacity for sigmoid growth phase
  
  times <- c(seq(Tmin, Tmax, step_size))
  
  k_time <- data.frame(times = times, k = rep(0, length(times)))
  k_time <- k_time %>% mutate(k = case_when(times <= 35 ~ k1, 
                                            times > 35 ~ -k2))
  
  k_t <- approxfun(k_time$times, k_time$k, rule = 2)
  
  derivs <- function(times, y, pars, k_t) {
    with(as.list(c(pars, y)), {
      k <- k_t(times)   # Get k value based on time
      if (times < 35) {
        dA <- k * A * (1 - A / C) # Sigmoid growth phase
      } else {
        dA <- k * A # Exponential decay phase
      }
      return(list(c(dA)))
    })
  }
  
  y <- c(A = A0) # Initial observation
  
  out <- ode(y = y, parms = pars, times = times, func = derivs, k_t = k_t)
  as.data.frame(out)
}
```

```{r}
## Sampling function to simulate the CI for population dynamics
sample_ab <- function(pop, num){
  
  inds_mean <- which(rownames(pop) %in% c("k1_pop","k2_pop","A0_pop", 'peak_pop')) #row number of parameters
  inds_sd <- which(rownames(pop) %in% c("omega_k1","omega_k2","omega_A0", "omega_peak"))

  pars <- matrix(0, num+1, length(inds_mean))
  
  for (i in 1:length(inds_mean)) {
    mean_par <- pop$value[inds_mean[i]]
    sd_par <- pop$value[inds_sd[i]]
    #sd_par <- pop$se_sa[inds_mean[i]] ####standard error of population parameter
    
    if (i==1) {
      
      log_k1 = log(mean_par)
      pars[1:num, i] <- exp(rnorm(num, mean = log_k1, sd=sd_par))
      pars[num+1, i] <- exp(log_k1)
    } 
    
    else if (i==2 ) {

      log_k2 = log(mean_par)
      pars[1:num, i] <- exp(rnorm(num, mean = log_k2, sd=sd_par))
      pars[num+1, i] <- exp(log_k2)
    } 
    
    
    else if (i==3) {
      
      log_A0 = log(mean_par)
      pars[1:num, i] <- exp(rnorm(num, mean=log_A0, sd=sd_par))
      pars[num+1, i] <- exp(log_A0)
    }
    
    else if (i==4 ) {
      
      log_C = log(mean_par)
      pars[1:num, i] <- exp(rnorm(num, mean=log_C, sd=sd_par))
      pars[num+1, i] <- exp(log_C)
    } 
  }
  return(pars)
}
```

############# Function to store output in column form ##############
```{r}
run_ODE_control <- function(pars){
  total_AL <- matrix(NA,nrow=length(seq(Tmin,Tmax,step_size)),ncol=n)
  for(i in 1:n){
    out <- ode_ab_pop(pars[i, ])
  total_AL[,i] <- out$A
  }
  return(total_AL)
}
```




#######Read individual data#########
```{r}
original <- read.csv("demo.csv") 
Est <- read.csv("IndividualParameters/estimatedIndividualParameters.txt",  sep = ",", comment.char = "", header = T)
Simulated <- read.csv("IndividualParameters/simulatedIndividualParameters.txt" ,sep = ",", comment.char = "", header = T)
max(Simulated$rep) #See how many simulated parameters for each individual
```
#######Individual plot function ########
```{r}


ind_fit_plt<-function(Estimated,Simulated){
  
  Fit <- list()
  for(i in 1:nrow(Estimated)){
    pars <- c(k1=Estimated$k1_mode[i],
              k2=Estimated$k2_mode[i],
              A0=Estimated$A0_mode[i],
              C = Estimated$peak_mode[i])
    fitted <- ode_ab_pop(pars)
    d1 <- data.frame(Days=(times),y=(fitted$A))
    Code <- Estimated$id[i]
    
    S <- 94 ###94 repeats
    P <- matrix(NA,nrow=length(times),ncol=S)
    
    
   for(j in 1:S){
      pars <- c(k1=Simulated$k1[j+S*(i-1)],k2=Simulated$k2[j+S*(i-1)],A0=Simulated$A0[j+S*(i-1)],C=Simulated$peak[j+S*(i-1)])
      out  <- ode_ab_pop(pars)
      P[,j] <- out$A
    }
    
    Min  <- apply(P,1,function(x){quantile(x,0.005)})
    Max  <- apply(P,1,function(x){quantile(x,0.995)})
    
    fit <- cbind(d1,Min,Max,Code)
    fit$Max[fit$Max> 100] <- 100
    fit$Min[fit$Min> 100] <- 100
    
    Fit[[i]] <- data.frame(fit)
  }
  
  ind_fit_unlist <- map_df(Fit, ~as.data.frame(.x))
  ind_fit_unlist <- ind_fit_unlist[order(ind_fit_unlist$Code, ind_fit_unlist$Days), ]
  return(ind_fit_unlist)
}

individual_fit <- ind_fit_plt(Est, Simulated)
```

######################################
############ S-Fig-4##################
######################################

```{r}
individual_fit_with_code <- individual_fit %>% rename(id = Code) %>% left_join(original[,c(1,5)], by = "id")

pdf("individual_plots_2.pdf", 14, 14)

for (i in seq(1, length(unique(individual_fit_with_code$Code)),length(unique(individual_fit_with_code$Code)))) {
  print(
   ggplot(individual_fit_with_code, aes(x = Days)) +
   geom_ribbon(aes(ymin = Min, ymax = Max), alpha = 0.3) +
   geom_line(aes(y = y), size = 1, alpha = 0.8) +
   geom_point(data = original, aes(x = day, y = igG), 
             shape = 16, size = 2, alpha = 2) +
  facet_wrap(~Code) +
  labs(
    title = "Individual Fit with Shaded Uncertainty",
    x = "Days",
    y = "IgG Binding %"
   
  ) +
 theme(axis.text = element_text(colour = "black"),
        axis.ticks = element_line(colour = "black"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position='none',
        axis.title.y = element_text(size=11,family="sans"),
        axis.title.x = element_text(size=11,family="sans"),
  theme_minimal() ))
  }
dev.off()
```
